//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeyawoPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblAdminSidebar
    {
        public int AdminSideBarId { get; set; }
        public string SidebarTitle { get; set; }
        public string CoverImageUrl { get; set; }
        public string ProfileImageUrl { get; set; }
    }
}
